name: Maven Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # Replaced SHA with version tag

      - name: Set up JDK
        uses: actions/setup-java@v4  # Replaced SHA with version tag
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Make mvnw executable
        run: chmod +x ./mvnw  # Fix for permission denied issue

      - name: Cache Maven dependencies
        uses: actions/cache@v4  # Replaced SHA with version tag
        with:
          path: |
            ~/.m2/repository
            target
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Run tests
        run: ./mvnw test
